---
title: "p8105_hw5_lz2657"
author: Lingyu Zhang
date: Nov 5, 2018
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(purrr)
library(broom)
```

## Problem 1

First, set up a dataframe containing all file names.

```{r problem1_read_file_names}
  df = as.tibble(list.files(path = "./data/"))

  df
```

Next, make a reading function, read in data for each subject and save the result as the "observe" variable.

```{r problem1_read_data}
read_csv_function = function(file_name){
  subject =
    read_csv(file = str_c("./data/", file_name)) %>%
    mutate(file = file_name)
}

df = mutate(df, observe = map(.x = df[[1,]], ~ read_csv_function(.x)))
```

Now tidy the result.

```{r problem1_tidy}
df = df%>%
  separate(value, into = c("arm", "number"), sep = "_") %>%
  mutate(number = substr(number, 1, 2)) %>%
  unnest %>%
  gather(key = week, value = data, week_1:week_8) %>%
  mutate(week = substr(week, 6, 6)) %>%
  select(arm, number, week, data)

df
```

Then we can make a spaghetti plot showing observations on each subject over time.

```{r problem1_plot}
ggplot(df, aes(x = week, y = data, color = number, group = number)) + 
  geom_line() + 
  facet_grid( ~ arm) + 
    labs(
      title = "subject observations over time",
      x = "week",
      y = "observation"
    ) +
    viridis::scale_color_viridis(
      name = "ID", 
      discrete = TRUE
    )
```
